In [136]:
from transformers import AutoModelForCausalLM, AutoTokenizer

model = AutoModelForCausalLM.from_pretrained("gpt2")
tokenizer = AutoTokenizer.from_pretrained("gpt2")
input_ids = tokenizer.encode("The president of USA is Barack Ob", return_tensors="pt")
input_ids

tensor([[ 464, 1893,  286, 4916,  318, 8732, 1835]])

In [137]:
tokenizer.batch_decode(input_ids)

['The president of USA is Barack Ob']

In [126]:
input_ids.shape

torch.Size([1, 7])

In [127]:
outputs = model.forward(input_ids)
# outputs = model.forward(input_ids, output_hidden_states=True)
outputs.logits.shape

torch.Size([1, 7, 50257])

In [128]:
outputs.logits[0, -1, :].argmax()

tensor(17485)

In [129]:
tokenizer.decode(outputs.logits[0, -1, :].argmax())

'amas'

In [131]:
# outputs.hidden_states[-1].shape

In [132]:
o2 = model.generate(input_ids, do_sample=False)
o2

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
/workspaces/distributed-speculative-inference/.venv/lib/python3.10/site-packages/transformers/generation/utils.py:1259: UserWarning: Using the model-agnostic default `max_length` (=20) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(


tensor([[  464,  1893,   286,  4916,   318,  8732,  1835, 17485,    11,   508,
           318,   262,   717,  5510,    12,  7437,  1893,    13,   198,   198]])

In [133]:
import torch

model.forward(
    torch.tensor([input_ids.tolist()[0] + [17485, 11, 508, 318, 262, 717]]),
    output_hidden_states=True,
).logits[0, -1, :].argmax()

tensor(5510)

In [134]:
# outputs.logits[0, :, :].shape
# argmax for each token in the sequence. should output a tensor of shape (1, 7)
outputs.logits[0, :, :].argmax(1)

tensor([  198,   286,   262,  6288,   257,  2486, 17485])

In [135]:
outputs.logits[0, :, :].argmax(dim=0)

tensor([0, 0, 0,  ..., 0, 0, 0])