In [5]:
from poc.actual.utils import decode
import torch

def print_decoded(tok_ids, model_name):
    out_str = "".join(decode(tok_ids, model_name))
    print(repr(out_str))

model_name = "meta-llama/Meta-Llama-3.1-70B-Instruct"
accepted_tok_ids = torch.tensor([  791, 16659,   649,   387,  3974,   477,  4200,    11,   719,   449,
          279, 28522, 14691,   304,  1690,  5596,   315,   279,  1917,    11,
         1690,  5220,   690,  3469,   369,  4200, 16659,   304,  2015,   311,
        30437,   279,  9041,   315, 17563,    13, 21382, 16659,  1101,  4546,
          459,  1358,   315, 22934,  1093,  1694,  3025,   311,  4667,   449,
         1274,   304,  2204,  5596,   315,   279,  1917,    13,  4815])
print_decoded(accepted_tok_ids, model_name)

'The meetings can be live or virtual, but with the pandemic continuing in many parts of the world, many companies will opt for virtual meetings in order to minimize the spread of illness. Virtual meetings also bring an array of advantages like being able to connect with people in different parts of the world. \n\n'


In [6]:
draft_tok_ids = torch.tensor([  791, 16659,   649,   387,  3974,   477,  4200,    11,   719,   449,
          279, 28522, 14691,   304,  1690,  5596,   315,   279,  1917,    11,
         1690,  5220,   690,  3469,   369,  4200, 16659,   304,  2015,   311,
        30437,   279,  9041,   315, 17563,    13, 21382, 16659,  1101,  4546,
          459,  1358,   315, 22934,  1093,  1694,  3025,   311,  4667,   449,
         1274,   304,  2204,  5596,   315,   279,  1917,    13,   720])
print_decoded(draft_tok_ids, model_name)

'The meetings can be live or virtual, but with the pandemic continuing in many parts of the world, many companies will opt for virtual meetings in order to minimize the spread of illness. Virtual meetings also bring an array of advantages like being able to connect with people in different parts of the world. \n'


In [7]:
print_decoded(torch.tensor([4815]), model_name)
print_decoded(torch.tensor([720]), model_name)

' \n\n'
' \n'


In [9]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer

PreTrainedTokenizerFast(name_or_path='meta-llama/Meta-Llama-3.1-70B-Instruct', vocab_size=128000, model_max_length=131072, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'bos_token': '<|begin_of_text|>', 'eos_token': '<|eot_id|>'}, clean_up_tokenization_spaces=True),  added_tokens_decoder={
	128000: AddedToken("<|begin_of_text|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	128001: AddedToken("<|end_of_text|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	128002: AddedToken("<|reserved_special_token_0|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	128003: AddedToken("<|reserved_special_token_1|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	128004: AddedToken("<|finetune_right_pad_id|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	128005: AddedToken("<|reserved_special_token

In [13]:
tokenizer.special_tokens_map_extended

{'bos_token': AddedToken("<|begin_of_text|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
 'eos_token': AddedToken("<|eot_id|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True)}

In [15]:
tokenizer.special_tokens_map

{'bos_token': '<|begin_of_text|>', 'eos_token': '<|eot_id|>'}

In [22]:
# get the special tokens
for tok in tokenizer.all_special_tokens:
    print(tok)
    print(tokenizer.convert_tokens_to_ids(tok))
    print()

<|begin_of_text|>
128000

<|eot_id|>
128009



In [26]:
dsi_len = len([128000,  39314,    374,    459,   7754,    430,  16964,    264,   3465,
             13,   9842,    264,   2077,    430,  36001,  45695,    279,   1715,
            382,  14711,  30151,    512,   3923,   1053,    387,    279,   1888,
            955,    315,  10368,    369,    264,   1732,    889,    706,  55652,
           1980,  14711,   6075,    512,   2520,    264,   1732,    449,  55652,
             11,    279,   1888,    955,    315,  10368,    374,   3629,   3428,
             12,  58400,   7640,    430,   1541,    956,   2231,  27639,  26800,
            389,    279,  35358,     13,   4314,    649,   2997,   1473,     16,
             13,   3146,  29353,   6108,  23783,  96618,  75800,     11,   7463,
          34548,    677,   1233,     11,    477,   5042,  11689,    304,    279,
           3090,    649,    387,   1633,  24629,     13,    578,  75720,   6709,
            315,   3090,  26338,    279,   5536,    389,  35358,     11,   3339,
            433,    459,  10728,   4676,    369,   1274,    449,  55652,    382,
             17,     13,   3146,     34,  16404,  96618,  17040,    661,  33162,
            477,   1701,    264,   1421,   3635,    306,  13260,    374,   2500,
           3428,     12,  58400,   3072,    430,    649,   1520,   7417,  41713,
           2890,    323,  20259,  24569,   2085,  10917,  27639,  26800,    389,
            279,  35358,    382,     18,     13,   3146,     56,  14361,  96618,
          30153,  27102,  23783,    649,   1520,   7417,  25152,     11,   8335,
             11,    323,   8333,     13,   9176,  27102,  34103,    649,    387,
          30464,    311,  29376,    279,   9669,  27070,    555,  55652,    382,
             19,     13,   3146,  79094,  34382,  96618,   1115,    374,    264,
           6435,     11,  36612,  10368,    430,  33511,   7351,     11,   5655,
          27027,     11,    323,  33862,     13,   1102,    649,   1520,   7417,
           8335,     11,  25152,     11,    323,  41713,   2890,    382,     20,
             13,   3146,  79616,  96618,   6104,   1579,     12,  58400,   4401,
           2643,    387,   2288,  93319,   9373,     11])
si_len = len([128000,  39314,    374,    459,   7754,    430,  16964,    264,   3465,
             13,   9842,    264,   2077,    430,  36001,  45695,    279,   1715,
            382,  14711,  30151,    512,   3923,   1053,    387,    279,   1888,
            955,    315,  10368,    369,    264,   1732,    889,    706,  55652,
           1980,  14711,   6075,    512,   2520,    264,   1732,    449,  55652,
             11,    279,   1888,    955,    315,  10368,    374,   3629,   3428,
             12,  58400,     11,  91490,  23783,    430,    527,  22443,    389,
            279,  35358,     13,   4314,    649,   2997,   1473,     16,     13,
            220,  10164,   6108,  23783,     25,  75800,     11,   7463,  34548,
            677,   1233,     11,    477,   5042,  11689,    304,    279,   3090,
            649,    387,   2294,   1606,    279,  75720,   6709,    315,   3090,
          26338,    279,   5536,    389,  35358,    627,     17,     13,    220,
          61070,     25,  17040,    661,  33162,    477,   1701,    264,   1421,
           3635,    306,  13260,    374,   2500,   3428,     12,  58400,   1648,
            311,   7417,  41713,  17479,   2085,  10917,  27639,  26800,    389,
            279,  35358,    627,     18,     13,    220,  13852,  11696,    950,
          29994,     25,   1556,  78883,    950,  29994,    374,    264,   3428,
             12,  58400,   5780,    430,   1675,  24031,   4401,   2085,    279,
           1579,     12,  58400,   8631,    389,    279,  35358,    627,     19,
             13,    220,  38673,    477,  37451,    988,     25,  30153,  11028,
            315,   1521,  23783,    649,   1520,   7417,  25152,     11,   8333,
             11,    323,   8335,     13,   9176,  27102,    323,  37451,    988,
           6989,    527,   6319,  11951,    369,   1274,    449,  55652,    627,
             20,     13,    220,  40155,     25,  10928,  23291,    649,    387,
          24629,     11,   5423,    422,   2884,    389,  10269,     11,  11113,
          27529,    311,  30437,   8631,    389,    279,  35358,    382,   2181,
            596,   7718,    311,   8666,    449,    264])
nonsi_len = len([128000,  39314,    374,    459,   7754,    430,  16964,    264,   3465,
             13,   9842,    264,   2077,    430,  36001,  45695,    279,   1715,
            382,  14711,  30151,    512,   3923,   1053,    387,    279,   1888,
            955,    315,  10368,    369,    264,   1732,    889,    706,  55652,
           1980,  14711,   6075,    512,   2520,    264,   1732,    449,  55652,
             11,    279,   1888,    955,    315,  10368,    374,   3629,   3428,
             12,  58400,   7640,    430,   1541,    956,   2231,  27639,   8631,
            389,    279,  35358,     13,   4314,    649,   2997,   1473,     16,
             13,   3146,  29353,   6108,  23783,  96618,  75800,    477,   3090,
          34548,    677,   1233,    527,   9250,   1606,    279,  75720,   6709,
            315,   3090,  26338,    279,   5536,    389,  35358,    627,     17,
             13,   3146,     34,  16404,  96618,  17040,    661,  33162,    477,
           1701,    264,   1421,   3635,    306,  13260,    374,   2500,   3428,
             12,  58400,   3072,    430,    649,   1520,   7417,  41713,   2890,
           2085,  94791,    279,  35358,    627,     18,     13,   3146,     56,
          14361,  96618,  30153,  27102,  23783,    649,   1520,   7417,  25152,
            323,   8333,   2085,  10917,  27639,  26800,    389,    279,  35358,
             13,   1102,    596,   7718,    311,    990,    449,    264,  27102,
          33315,    889,  31869,  55652,    323,    649,   5719,  34103,  28178,
            627,     19,     13,   3146,  79094,  34382,  96618,   1115,    374,
            264,   6435,     11,  36612,  10368,    430,  33511,   7351,    449,
           5655,  27027,    323,    649,   1520,   7417,   8335,    323,   8108,
          70334,    627,     20,     13,   3146,  79616,  96618,   6104,   1579,
             12,  58400,   4401,   2643,    539,    387,  14791,     11,  11689,
             11,   5423,    389,  10269,  27529,     11,    649,    387,    264,
           1695,   3072,     13,   1102,    596,   7718,    311,  10051,  10882,
             11,  33445,  15653,    382,  10438,   6041])

print(f"DSI: {dsi_len}, SI: {si_len}, NonSI: {nonsi_len}")

DSI: 240, SI: 240, NonSI: 240


In [28]:
shared_prefix = torch.tensor([128000,  39314,    374,    459,   7754,    430,  16964,    264,   3465,
             13,   9842,    264,   2077,    430,  36001,  45695,    279,   1715,
            382,  14711,  30151,    512,   3923,   1053,    387,    279,   1888,
            955,    315,  10368,    369,    264,   1732,    889,    706,  55652,
           1980,  14711,   6075,    512,   2520,    264,   1732,    449,  55652,
             11,    279,   1888,    955,    315,  10368,    374,   3629,   3428,
             12,  58400])
shared_prefix_len = len(shared_prefix)
print(f"Shared prefix: {shared_prefix_len}")
print_decoded(shared_prefix, model_name)

Shared prefix: 56
'Below is an instruction that describes a task. Write a response that appropriately completes the request.\n\n### Instruction:\nWhat would be the best type of exercise for a person who has arthritis?\n\n### Response:\nFor a person with arthritis, the best type of exercise is often low-impact'


In [33]:
# Manager: Received response Response(id=5406c944-aa93-419d-b8fa-4df8518e27ed, timestamp=1727102194.7143414, request_timestamp=1727102186.7004025, is_draft=False, scores_shape=torch.Size([1, 84, 128256]), tok_ids:
request = torch.tensor([128000,  39314,    374,    459,   7754,    430,  16964,    264,   3465,
             13,   9842,    264,   2077,    430,  36001,  45695,    279,   1715,
            382,  14711,  30151,    512,   3923,   1053,    387,    279,   1888,
            955,    315,  10368,    369,    264,   1732,    889,    706,  55652,
           1980,  14711,   6075,    512,   2520,    264,   1732,    449,  55652,
             11,    279,   1888,    955,    315,  10368,    374,   3629,   3428,
             12,  58400,   7640,    430,   1541,    956,   2231,  27639,   8631,
            389,    279,  35358,     13,   1115,    649,   2997,  24269,     11,
          33162,     11,    477,   1701,    459,  78883,    950,  29994,     13,
           4314,  23783,    649, 1])
response = torch.tensor([128000,  39314,    374,    459,   7754,    430,  16964,    264,   3465,
             13,   9842,    264,   2077,    430,  36001,  45695,    279,   1715,
            382,  14711,  30151,    512,   3923,   1053,    387,    279,   1888,
            955,    315,  10368,    369,    264,   1732,    889,    706,  55652,
           1980,  14711,   6075,    512,   2520,    264,   1732,    449,  55652,
             11,    279,   1888,    955,    315,  10368,    374,   3629,   3428,
             12,  58400,   7640,    430,   1541,    956,   2231,  27639,  26800,
            389,    279,  35358,     13,   4314,    649,   2997,   1473,     11,
          33162,     11,    477,   1701,    459,  78883,    950,  29994,     13,
           4314,  23783,    649,   1520])
request.shape, response.shape

(torch.Size([85]), torch.Size([85]))

In [49]:
request[-25:]

tensor([ 2231, 27639,  8631,   389,   279, 35358,    13,  1115,   649,  2997,
        24269,    11, 33162,    11,   477,  1701,   459, 78883,   950, 29994,
           13,  4314, 23783,   649,     1])

In [47]:
response[: -25 + 1]

tensor([128000,  39314,    374,    459,   7754,    430,  16964,    264,   3465,
            13,   9842,    264,   2077,    430,  36001,  45695,    279,   1715,
           382,  14711,  30151,    512,   3923,   1053,    387,    279,   1888,
           955,    315,  10368,    369,    264,   1732,    889,    706,  55652,
          1980,  14711,   6075,    512,   2520,    264,   1732,    449,  55652,
            11,    279,   1888,    955,    315,  10368,    374,   3629,   3428,
            12,  58400,   7640,    430,   1541,    956,   2231])

In [35]:
request == response

tensor([ True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True, False,  True,  True,  True,  True, False,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True, False])

In [37]:
# Index of the first different token
torch.argwhere(request != response).flatten()[0]

tensor(62)

In [38]:
(request == response)[:63]

tensor([ True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True, False])

In [39]:
request[:63]

tensor([128000,  39314,    374,    459,   7754,    430,  16964,    264,   3465,
            13,   9842,    264,   2077,    430,  36001,  45695,    279,   1715,
           382,  14711,  30151,    512,   3923,   1053,    387,    279,   1888,
           955,    315,  10368,    369,    264,   1732,    889,    706,  55652,
          1980,  14711,   6075,    512,   2520,    264,   1732,    449,  55652,
            11,    279,   1888,    955,    315,  10368,    374,   3629,   3428,
            12,  58400,   7640,    430,   1541,    956,   2231,  27639,   8631])

In [40]:
response[:63]

tensor([128000,  39314,    374,    459,   7754,    430,  16964,    264,   3465,
            13,   9842,    264,   2077,    430,  36001,  45695,    279,   1715,
           382,  14711,  30151,    512,   3923,   1053,    387,    279,   1888,
           955,    315,  10368,    369,    264,   1732,    889,    706,  55652,
          1980,  14711,   6075,    512,   2520,    264,   1732,    449,  55652,
            11,    279,   1888,    955,    315,  10368,    374,   3629,   3428,
            12,  58400,   7640,    430,   1541,    956,   2231,  27639,  26800])

NameError: name 'model' is not defined