# Scores

#### Drafter (`generate`)

`n=curr_lookahead`

In [8]:
from transformers import AutoModelForCausalLM, AutoTokenizer

model_name = "gpt2"
tokenizer = AutoTokenizer.from_pretrained(model_name)
tok_ids = tokenizer.encode("Hello, my name is", return_tensors="pt")
print(tok_ids)
print(tok_ids.shape)

tensor([[15496,    11,   616,  1438,   318]])
torch.Size([1, 5])


/home/root/.cache/pypoetry/virtualenvs/distributed-speculative-inference-w7-NjH3e-py3.11/lib/python3.11/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


In [9]:
import torch

model = AutoModelForCausalLM.from_pretrained(model_name)
outputs = model.generate(
    input_ids=tok_ids,
    attention_mask=torch.ones_like(tok_ids),
    max_new_tokens=10,
    do_sample=False,
    use_cache=False,
    return_dict_in_generate=True,
    output_logits=False,
    output_scores=True,
    output_hidden_states=False,
    output_attentions=False,
)
print(outputs)
# print(outputs.shape)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


GenerateDecoderOnlyOutput(sequences=tensor([[15496,    11,   616,  1438,   318,  1757,    13,   314,  1101,   257,
          6260,    11,   290,   314,  1101]]), scores=(tensor([[-68.4289, -69.0398, -73.2529,  ..., -76.9532, -77.1063, -70.0094]]), tensor([[-65.0738, -66.4413, -71.7042,  ..., -79.9795, -77.5036, -68.6040]]), tensor([[-130.1885, -129.3489, -131.3793,  ..., -141.4481, -142.7361,
         -124.0823]]), tensor([[-131.9186, -130.0697, -135.7836,  ..., -141.5105, -134.1392,
         -133.0101]]), tensor([[-112.3013, -111.0004, -114.8719,  ..., -119.3571, -119.8524,
         -112.7859]]), tensor([[-108.1326, -106.7145, -110.4225,  ..., -115.2539, -114.6338,
         -107.9903]]), tensor([[ -95.4683,  -96.0403, -103.7460,  ..., -108.3876, -107.8743,
          -99.9795]]), tensor([[-83.7534, -83.9494, -85.5162,  ..., -88.0616, -89.6183, -82.4906]]), tensor([[-110.4278, -109.9855, -113.4881,  ..., -116.3650, -116.2361,
         -110.5043]]), tensor([[-144.8037, -143.3270, -147.85

In [10]:
# print all the fields of the `outputs` object
print(outputs.keys())

odict_keys(['sequences', 'scores'])


In [11]:
print(outputs.sequences)
print(tokenizer.batch_decode(outputs.sequences))

tensor([[15496,    11,   616,  1438,   318,  1757,    13,   314,  1101,   257,
          6260,    11,   290,   314,  1101]])
["Hello, my name is John. I'm a writer, and I'm"]


In [12]:
print(type(outputs.scores))
print(outputs.scores)

<class 'tuple'>
(tensor([[-68.4289, -69.0398, -73.2529,  ..., -76.9532, -77.1063, -70.0094]]), tensor([[-65.0738, -66.4413, -71.7042,  ..., -79.9795, -77.5036, -68.6040]]), tensor([[-130.1885, -129.3489, -131.3793,  ..., -141.4481, -142.7361,
         -124.0823]]), tensor([[-131.9186, -130.0697, -135.7836,  ..., -141.5105, -134.1392,
         -133.0101]]), tensor([[-112.3013, -111.0004, -114.8719,  ..., -119.3571, -119.8524,
         -112.7859]]), tensor([[-108.1326, -106.7145, -110.4225,  ..., -115.2539, -114.6338,
         -107.9903]]), tensor([[ -95.4683,  -96.0403, -103.7460,  ..., -108.3876, -107.8743,
          -99.9795]]), tensor([[-83.7534, -83.9494, -85.5162,  ..., -88.0616, -89.6183, -82.4906]]), tensor([[-110.4278, -109.9855, -113.4881,  ..., -116.3650, -116.2361,
         -110.5043]]), tensor([[-144.8037, -143.3270, -147.8548,  ..., -154.3876, -147.2709,
         -145.4146]]))


In [13]:
print(len(outputs.scores))
print(outputs.scores[0].shape)
# Stack the scores as follows.
# Instead of the existing shape of the a score (batch=1, vocab), the first dimension is
# the sequence and the second is the vocab (num_of_scores, vocab). Since the batch size
# is always 1, we can omit the batch dimension. Note that we might get `num_of_scores=1`
torch.stack(outputs.scores, dim=0).squeeze(1).shape

10
torch.Size([1, 50257])


torch.Size([10, 50257])

In [14]:
argmax = [s.argmax() for s in outputs.scores]
print(argmax)
print(tokenizer.batch_decode(argmax))

[tensor(1757), tensor(13), tensor(314), tensor(1101), tensor(257), tensor(6260), tensor(11), tensor(290), tensor(314), tensor(1101)]
[' John', '.', ' I', "'m", ' a', ' writer', ',', ' and', ' I', "'m"]


#### Verifier (`forward`)

Needs to provide the `n` scores corresponding to 
- the last `n-1` tokens, and
- the next token

In [44]:

print(f"{tok_ids=}")
print(f"{tok_ids.shape=}")

tok_ids=tensor([[15496,    11,   616,  1438,   318]])
tok_ids.shape=torch.Size([1, 5])


In [33]:
outputs = model.forward(
    input_ids=tok_ids,
    attention_mask=torch.ones_like(tok_ids),
    use_cache=False,
    return_dict=True,
    output_hidden_states=False,
    output_attentions=False,
)
outputs

CausalLMOutputWithCrossAttentions(loss=None, logits=tensor([[[ -35.2363,  -35.3266,  -38.9754,  ...,  -44.4645,  -43.9975,
           -36.4580],
         [-112.6171, -114.5832, -116.5725,  ..., -119.0128, -118.8059,
          -111.6917],
         [ -88.7435,  -89.8644,  -93.1977,  ...,  -92.3839,  -96.1782,
           -92.1273],
         [ -51.9342,  -53.6023,  -59.3668,  ...,  -62.4015,  -66.0021,
           -57.7503],
         [ -68.4289,  -69.0398,  -73.2529,  ...,  -76.9532,  -77.1063,
           -70.0094]]], grad_fn=<UnsafeViewBackward0>), past_key_values=None, hidden_states=None, attentions=None, cross_attentions=None)

In [40]:
outputs.logits.shape

torch.Size([1, 5, 50257])

In [46]:
logits_argmax = outputs.logits.argmax(dim=-1)
logits_argmax

tensor([[  11,  314, 1438,  318, 1757]])

In [71]:
# Add the first token at the beginning of the logits_argmax
torch.cat((tok_ids[0, :1], logits_argmax[0, :])).unsqueeze(0)

tensor([[15496,    11,   314,  1438,   318,  1757]])

`model.forward(..., return_dict=True).logits` is a tensor of shape (batch_size, seq_len, vocab_size)

In [35]:
print(f"{type(outputs.logits)=}")
print(f"{len(outputs.logits)=}")
print(f"{type(outputs.logits[0])=}")
print(f"{len(outputs.logits[0])=}")
print(f"{len(outputs.logits[-1])=}")
print(f"{outputs.logits[0][0].shape=}")

type(outputs.logits)=<class 'torch.Tensor'>
len(outputs.logits)=1
type(outputs.logits[0])=<class 'torch.Tensor'>
len(outputs.logits[0])=5
len(outputs.logits[-1])=5
outputs.logits[0][0].shape=torch.Size([50257])


# Preemption

Proof-of-concept that we can preempt a long-running call to `transformers`.